Django_HW11/Django_HW11/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstapp.urls"))
] + static("/", document_root=settings.MEDIA_ROOT)

Django_HW11/firstapp/urls.py
from django.urls import path
from . import views

app_name="firstapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_movie, name="add_movie"),
    path("<int:pk>/", views.movie_detail, name="movie_detail"),
    path('<int:pk>/edit/', views.edit_movie, name='edit_movie'),
    path('<int:pk>/delete/', views.delete_movie, name='delete_movie'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_review'),
]

Django_HW11/firstapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    release = models.DateField()
    country = models.CharField(max_length=100)
    img = models.ImageField(upload_to="media/")
    genre = models.ManyToManyField(Genre, related_name="Movie")  # ← ManyToMany
    rating = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ],
        default=1
    )

    def __str__(self):
        return self.title

    @property
    def review_count(self):
        return self.reviews.count()


class Review(models.Model):
    name = models.CharField(max_length=50)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    film = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="Review")

    class Meta:
        permissions = [
            ("can_moderate_reviews", "Can moderate reviews"),
        ]

    def __str__(self):
        return f"Review by {self.name}"

Django_HW11/firstapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ["title", "description", "release", "rating", "country", "img", "genre"]
        widgets = {
            'release': forms.DateInput(attrs={'type': 'date'}),
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5})
        }

class ReviewForm(forms.Form):
    name = forms.CharField(max_length=50)
    text = forms.CharField(max_length=1000) 

Django_HW11/firstapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from datetime import datetime

# Create your views here.
from .models import Movie, Review
from .forms import MovieForm, ReviewForm

def index(request):
    sort = request.GET.get('sort')

    if sort == 'rating':
        movies = Movie.objects.all().order_by('-rating')
    elif sort == 'date':
        movies = Movie.objects.all().order_by('-release')
    else:
        movies = Movie.objects.all()

    return render(request, 'index.html', {'movies': movies})

def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST)

        if form.is_valid():
            mname = form.cleaned_data["name"] + f"{movie.Review.count()}" 
            mdate = datetime.now()
            mtext = form.cleaned_data["text"]

            a = Review(name=mname, date=mdate, text=mtext, film=movie)
            a.save()
            return redirect("firstapp:movie_detail", pk=pk)
    
    form = ReviewForm()
    return render(request, "movie_detail.html", { "form": form, "movie" : movie, "reviews": movie.Review.all(), "Genres": movie.genre.all()})

def add_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("firstapp:index")
    else:
        form = MovieForm()

    return render(request, "add_movie.html", {"form": form})

def edit_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('firstapp:movie_detail', pk=movie.pk)
    else:
        form = MovieForm(instance=movie)

    return render(request, 'edit_movie.html', {'form': form, 'movie': movie})


def delete_movie(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('firstapp:index')
    return render(request, 'delete_movie.html', {'movie': movie})

def delete_comment(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.method == 'POST':
        review.delete()
        return redirect("firstapp:index")
    return render(request, "delete_review.html", {"review": review})

Django_HW11/firstapp/templates/add_movie.html
<h1>Add new movie</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Add </button>
</form>

Django_HW11/firstapp/templates/delete_movie.html
<h1>Delete "{{ movie.title }}"?</h1>

<form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'firstapp:movie_detail' movie.pk %}">Cancel</a>
</form>

Django_HW11/firstapp/templates/delete_review.html
<form method="post" enctype="multipart/form-data">
    <h1>Delete Comment?</h1>
    {% csrf_token %}
    {% include "review.html" with review=review delete=False %}
    <button type="submit">Yes </button>
    <a href="/"> Cancel </button>
</form>

Django_HW11/firstapp/templates/edit_movie.html
<h1>Edit "{{ movie.title }}"</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

Django_HW11/firstapp/templates/index.html
<a href="{% url 'firstapp:add_movie' %}">Add movie</a>

<h2>Sort:</h2>
<a href="?sort=rating">Rating</a>,
<a href="?sort=date">Date</a>

<hr>

<div style="display: flex; flex-wrap: wrap; gap: 20px;">
    {% for m in movies %}
    <div style="border: 1px solid #ccc; padding: 10px; width: 200px;">
        <a href="{% url 'firstapp:movie_detail' m.pk %}">
            <img src="{{ m.img.url }}" width="200">
            <h3>{{ m.title }}</h3>
        </a>
        <p>Date: {{ m.release }}</p>
        <p>Country: {{ m.country }}</p>
        <p><strong>Rating: {{ m.rating }}/5</strong></p>
    </div>
    {% endfor %}
</div>

Django_HW11/firstapp/templates/movie_detail.html
<div style="border: 1px solid #ccc; padding: 10px;">
    <h1>{{ movie.title }}</h1>

    <img src="{{ movie.img.url }}" width="300">
    <p><strong>Genres:</strong></p>
    {% for genre in Genres %}
        <p> - {{ genre }}</p>
    {% endfor %}

    <p><strong>Release date:</strong> {{ movie.release }}</p>
    <p><strong>Country:</strong> {{ movie.country }}</p>
    <p><strong>Rating:</strong> {{ movie.rating }}/5</p>

    <p>{{ movie.description }}</p>

    <a href="{% url 'firstapp:edit_movie' movie.pk %}">Edit</a> |
    <a href="{% url 'firstapp:delete_movie' movie.pk %}">Delete</a> |
    <a href="{% url 'firstapp:index' %}">Back</a>
</div>

<div style="border: 1px solid #ccc; padding: 10px;">
    <div style="border: 1px solid #ccc; padding: 10px;">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>Add Comment</h3>
            {{ form.as_p }}
            <button type="submit">Yes</button>
        </form>
    </div>
    {% for review in reviews %}
        {% include "review.html" with review=review delete=True %}
    {% endfor %}
</div>

Django_HW11/firstapp/templates/review.html
<div style="border: 1px solid #ccc; padding: 10px;">
    <p><strong>{{ review.name }}:</strong> {{ review.text }}</p>
    <p>{{ review.date }}</p>
    {% if delete %} <a href="/delete_comment/{{ review.id }}/"> Delete? </a> {% endif %}
</div>